/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/*! @name PORTE24 (number 20), J1[12]/D5-TPM0_CH0
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_S3_PS_FGPIO FGPIOE              /*!<@brief FGPIO peripheral base pointer */
#define BOARD_S3_PS_GPIO GPIOE                /*!<@brief GPIO peripheral base pointer */
#define BOARD_S3_PS_GPIO_PIN_MASK (1U << 24U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_S3_PS_PORT PORTE                /*!<@brief PORT peripheral base pointer */
#define BOARD_S3_PS_PIN 24U                   /*!<@brief PORT pin number */
#define BOARD_S3_PS_PIN_MASK (1U << 24U)      /*!<@brief PORT pin mask */
                                              /* @} */

/*! @name PORTE31 (number 19), J2[2]/D8-TPM0_CH4
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_S3_G2_FGPIO FGPIOE              /*!<@brief FGPIO peripheral base pointer */
#define BOARD_S3_G2_GPIO GPIOE                /*!<@brief GPIO peripheral base pointer */
#define BOARD_S3_G2_GPIO_PIN_MASK (1U << 31U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_S3_G2_PORT PORTE                /*!<@brief PORT peripheral base pointer */
#define BOARD_S3_G2_PIN 31U                   /*!<@brief PORT pin number */
#define BOARD_S3_G2_PIN_MASK (1U << 31U)      /*!<@brief PORT pin mask */
                                              /* @} */

/*! @name PORTA12 (number 28), J1[6]/D2-TPM1_CH0
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_S3_PG_FGPIO FGPIOA              /*!<@brief FGPIO peripheral base pointer */
#define BOARD_S3_PG_GPIO GPIOA                /*!<@brief GPIO peripheral base pointer */
#define BOARD_S3_PG_GPIO_PIN_MASK (1U << 12U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_S3_PG_PORT PORTA                /*!<@brief PORT peripheral base pointer */
#define BOARD_S3_PG_PIN 12U                   /*!<@brief PORT pin number */
#define BOARD_S3_PG_PIN_MASK (1U << 12U)      /*!<@brief PORT pin mask */
                                              /* @} */

/*! @name PORTE16 (number 8), J4[2]/A0-ADC0_SE1
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_S2_PS_FGPIO FGPIOE              /*!<@brief FGPIO peripheral base pointer */
#define BOARD_S2_PS_GPIO GPIOE                /*!<@brief GPIO peripheral base pointer */
#define BOARD_S2_PS_GPIO_PIN_MASK (1U << 16U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_S2_PS_PORT PORTE                /*!<@brief PORT peripheral base pointer */
#define BOARD_S2_PS_PIN 16U                   /*!<@brief PORT pin number */
#define BOARD_S2_PS_PIN_MASK (1U << 16U)      /*!<@brief PORT pin mask */
                                              /* @} */

/*! @name PORTE20 (number 9), J4[6]/A2-ADC0_SE0
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_S1_PR_FGPIO FGPIOE              /*!<@brief FGPIO peripheral base pointer */
#define BOARD_S1_PR_GPIO GPIOE                /*!<@brief GPIO peripheral base pointer */
#define BOARD_S1_PR_GPIO_PIN_MASK (1U << 20U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_S1_PR_PORT PORTE                /*!<@brief PORT peripheral base pointer */
#define BOARD_S1_PR_PIN 20U                   /*!<@brief PORT pin number */
#define BOARD_S1_PR_PIN_MASK (1U << 20U)      /*!<@brief PORT pin mask */
                                              /* @} */

/*! @name PORTE21 (number 10), J4[8]/A3-ADC0_SE4A
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_S1_PS_FGPIO FGPIOE              /*!<@brief FGPIO peripheral base pointer */
#define BOARD_S1_PS_GPIO GPIOE                /*!<@brief GPIO peripheral base pointer */
#define BOARD_S1_PS_GPIO_PIN_MASK (1U << 21U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_S1_PS_PORT PORTE                /*!<@brief PORT peripheral base pointer */
#define BOARD_S1_PS_PIN 21U                   /*!<@brief PORT pin number */
#define BOARD_S1_PS_PIN_MASK (1U << 21U)      /*!<@brief PORT pin mask */
                                              /* @} */

/*! @name PORTB1 (number 36), J4[10]/A4-I2C0_SDA/ADC0_SE9
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_S1_G1_FGPIO FGPIOB             /*!<@brief FGPIO peripheral base pointer */
#define BOARD_S1_G1_GPIO GPIOB               /*!<@brief GPIO peripheral base pointer */
#define BOARD_S1_G1_GPIO_PIN_MASK (1U << 1U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_S1_G1_PORT PORTB               /*!<@brief PORT peripheral base pointer */
#define BOARD_S1_G1_PIN 1U                   /*!<@brief PORT pin number */
#define BOARD_S1_G1_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                             /* @} */

/*! @name PORTB0 (number 35), J4[12]/A5-I2C0_SCL/ADC0_SE8
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_S1_O_FGPIO FGPIOB             /*!<@brief FGPIO peripheral base pointer */
#define BOARD_S1_O_GPIO GPIOB               /*!<@brief GPIO peripheral base pointer */
#define BOARD_S1_O_GPIO_PIN_MASK (1U << 0U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_S1_O_PORT PORTB               /*!<@brief PORT peripheral base pointer */
#define BOARD_S1_O_PIN 0U                   /*!<@brief PORT pin number */
#define BOARD_S1_O_PIN_MASK (1U << 0U)      /*!<@brief PORT pin mask */
                                            /* @} */

/*! @name PORTD7 (number 64), J2[20]/J23[1]/D15-I2C1_SCL
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_S2_G2_FGPIO FGPIOD             /*!<@brief FGPIO peripheral base pointer */
#define BOARD_S2_G2_GPIO GPIOD               /*!<@brief GPIO peripheral base pointer */
#define BOARD_S2_G2_GPIO_PIN_MASK (1U << 7U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_S2_G2_PORT PORTD               /*!<@brief PORT peripheral base pointer */
#define BOARD_S2_G2_PIN 7U                   /*!<@brief PORT pin number */
#define BOARD_S2_G2_PIN_MASK (1U << 7U)      /*!<@brief PORT pin mask */
                                             /* @} */

/*! @name PORTD6 (number 63), J2[18]/J24[1]/D14-I2C1_SDA
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_S2_G1_FGPIO FGPIOD             /*!<@brief FGPIO peripheral base pointer */
#define BOARD_S2_G1_GPIO GPIOD               /*!<@brief GPIO peripheral base pointer */
#define BOARD_S2_G1_GPIO_PIN_MASK (1U << 6U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_S2_G1_PORT PORTD               /*!<@brief PORT peripheral base pointer */
#define BOARD_S2_G1_PIN 6U                   /*!<@brief PORT pin number */
#define BOARD_S2_G1_PIN_MASK (1U << 6U)      /*!<@brief PORT pin mask */
                                             /* @} */

/*! @name PORTC5 (number 50), J2[12]/D13-SPI0_SCK
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_S2_O_FGPIO FGPIOC             /*!<@brief FGPIO peripheral base pointer */
#define BOARD_S2_O_GPIO GPIOC               /*!<@brief GPIO peripheral base pointer */
#define BOARD_S2_O_GPIO_PIN_MASK (1U << 5U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_S2_O_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define BOARD_S2_O_PIN 5U                   /*!<@brief PORT pin number */
#define BOARD_S2_O_PIN_MASK (1U << 5U)      /*!<@brief PORT pin mask */
                                            /* @} */

/*! @name PORTC7 (number 52), J2[10]/D12-SPI0_MISO
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_S2_R_FGPIO FGPIOC             /*!<@brief FGPIO peripheral base pointer */
#define BOARD_S2_R_GPIO GPIOC               /*!<@brief GPIO peripheral base pointer */
#define BOARD_S2_R_GPIO_PIN_MASK (1U << 7U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_S2_R_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define BOARD_S2_R_PIN 7U                   /*!<@brief PORT pin number */
#define BOARD_S2_R_PIN_MASK (1U << 7U)      /*!<@brief PORT pin mask */
                                            /* @} */

/*! @name PORTC6 (number 51), J2[8]/D11-SPI0_MOSI
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_S3_G1_FGPIO FGPIOC             /*!<@brief FGPIO peripheral base pointer */
#define BOARD_S3_G1_GPIO GPIOC               /*!<@brief GPIO peripheral base pointer */
#define BOARD_S3_G1_GPIO_PIN_MASK (1U << 6U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_S3_G1_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define BOARD_S3_G1_PIN 6U                   /*!<@brief PORT pin number */
#define BOARD_S3_G1_PIN_MASK (1U << 6U)      /*!<@brief PORT pin mask */
                                             /* @} */

/*! @name PORTC4 (number 49), J2[6]/D10-SPI0_CS0
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_S3_O_FGPIO FGPIOC             /*!<@brief FGPIO peripheral base pointer */
#define BOARD_S3_O_GPIO GPIOC               /*!<@brief GPIO peripheral base pointer */
#define BOARD_S3_O_GPIO_PIN_MASK (1U << 4U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_S3_O_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define BOARD_S3_O_PIN 4U                   /*!<@brief PORT pin number */
#define BOARD_S3_O_PIN_MASK (1U << 4U)      /*!<@brief PORT pin mask */
                                            /* @} */

/*! @name PORTC8 (number 53), J1[16]/D7-TPM0_CH4/CMP0_IN2
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_S2_PG_FGPIO FGPIOC             /*!<@brief FGPIO peripheral base pointer */
#define BOARD_S2_PG_GPIO GPIOC               /*!<@brief GPIO peripheral base pointer */
#define BOARD_S2_PG_GPIO_PIN_MASK (1U << 8U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_S2_PG_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define BOARD_S2_PG_PIN 8U                   /*!<@brief PORT pin number */
#define BOARD_S2_PG_PIN_MASK (1U << 8U)      /*!<@brief PORT pin mask */
                                             /* @} */

/*! @name PORTC9 (number 54), J1[14]/D6-TPM0_CH5/CMP0_IN3
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_S2_PR_FGPIO FGPIOC             /*!<@brief FGPIO peripheral base pointer */
#define BOARD_S2_PR_GPIO GPIOC               /*!<@brief GPIO peripheral base pointer */
#define BOARD_S2_PR_GPIO_PIN_MASK (1U << 9U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_S2_PR_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define BOARD_S2_PR_PIN 9U                   /*!<@brief PORT pin number */
#define BOARD_S2_PR_PIN_MASK (1U << 9U)      /*!<@brief PORT pin mask */
                                             /* @} */

/*! @name PORTA1 (number 23), J1[2]/J25[1]/D0-UART0_RX
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_S1_G2_FGPIO FGPIOA             /*!<@brief FGPIO peripheral base pointer */
#define BOARD_S1_G2_GPIO GPIOA               /*!<@brief GPIO peripheral base pointer */
#define BOARD_S1_G2_GPIO_PIN_MASK (1U << 1U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_S1_G2_PORT PORTA               /*!<@brief PORT peripheral base pointer */
#define BOARD_S1_G2_PIN 1U                   /*!<@brief PORT pin number */
#define BOARD_S1_G2_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                             /* @} */

/*! @name PORTA2 (number 24), J1[4]/J26[1]/D1-UART0_TX
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_S1_R_FGPIO FGPIOA             /*!<@brief FGPIO peripheral base pointer */
#define BOARD_S1_R_GPIO GPIOA               /*!<@brief GPIO peripheral base pointer */
#define BOARD_S1_R_GPIO_PIN_MASK (1U << 2U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_S1_R_PORT PORTA               /*!<@brief PORT peripheral base pointer */
#define BOARD_S1_R_PIN 2U                   /*!<@brief PORT pin number */
#define BOARD_S1_R_PIN_MASK (1U << 2U)      /*!<@brief PORT pin mask */
                                            /* @} */

/*! @name PORTE25 (number 21), J1[8]/D3-TPM0_CH1
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_S3_PR_FGPIO FGPIOE              /*!<@brief FGPIO peripheral base pointer */
#define BOARD_S3_PR_GPIO GPIOE                /*!<@brief GPIO peripheral base pointer */
#define BOARD_S3_PR_GPIO_PIN_MASK (1U << 25U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_S3_PR_PORT PORTE                /*!<@brief PORT peripheral base pointer */
#define BOARD_S3_PR_PIN 25U                   /*!<@brief PORT pin number */
#define BOARD_S3_PR_PIN_MASK (1U << 25U)      /*!<@brief PORT pin mask */
                                              /* @} */

/*! @name PORTC0 (number 43), J4[4]/A1-ADC0_SE14
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_S1_PG_FGPIO FGPIOC             /*!<@brief FGPIO peripheral base pointer */
#define BOARD_S1_PG_GPIO GPIOC               /*!<@brief GPIO peripheral base pointer */
#define BOARD_S1_PG_GPIO_PIN_MASK (1U << 0U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_S1_PG_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define BOARD_S1_PG_PIN 0U                   /*!<@brief PORT pin number */
#define BOARD_S1_PG_PIN_MASK (1U << 0U)      /*!<@brief PORT pin mask */
                                             /* @} */

/*! @name PORTA5 (number 27), J2[4]/D9-TPM0_CH2
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_S3_R_FGPIO FGPIOA             /*!<@brief FGPIO peripheral base pointer */
#define BOARD_S3_R_GPIO GPIOA               /*!<@brief GPIO peripheral base pointer */
#define BOARD_S3_R_GPIO_PIN_MASK (1U << 5U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_S3_R_PORT PORTA               /*!<@brief PORT peripheral base pointer */
#define BOARD_S3_R_PIN 5U                   /*!<@brief PORT pin number */
#define BOARD_S3_R_PIN_MASK (1U << 5U)      /*!<@brief PORT pin mask */
                                            /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitLEDsPins(void);

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitButtonsPins(void);

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitTSIPins(void);

#define SOPT5_LPUART0RXSRC_CMP0 0x01u /*!<@brief LPUART0 Receive Data Source Select: CMP0 output */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitUSBPins(void);

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitACCEL_I2CPins(void);

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitMAGNET_I2CPins(void);

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitDEBUG_UARTPins(void);

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitTHERPins(void);

/*! @name PORTA18 (number 32), EXTAL_32KHZ
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_EXTAL0_PORT PORTA                /*!<@brief PORT peripheral base pointer */
#define BOARD_EXTAL0_PIN 18U                   /*!<@brief PORT pin number */
#define BOARD_EXTAL0_PIN_MASK (1U << 18U)      /*!<@brief PORT pin mask */
                                               /* @} */

/*! @name PORTA19 (number 33), XTAL_32KHZ
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_XTAL0_PORT PORTA                /*!<@brief PORT peripheral base pointer */
#define BOARD_XTAL0_PIN 19U                   /*!<@brief PORT pin number */
#define BOARD_XTAL0_PIN_MASK (1U << 19U)      /*!<@brief PORT pin mask */
                                              /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitOSCPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
